

/*
CREATE table IF NOT EXISTS user_account(
id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
first_name VARCHAR(20) NOT NULL,
last_name VARCHAR(20) NOT NULL,
age INTEGER NOT NULL 
);


-- drop database dass21_db WITH ( FORCE );
-- CREATE DATABASE dass21_db WITH OWNER = postgres;

-- Criação da tabela Participantes
CREATE TABLE IF NOT EXISTS Participantes (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    idade INT NOT NULL,
    genero VARCHAR(20) NOT NULL
);

-- Criação da tabela Respostas
CREATE TABLE IF NOT EXISTS Respostas (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participante_id INT,
    data_resposta TIMESTAMP NOT NULL,
    pontuacao_total_depressao INT NOT NULL,
    pontuacao_total_ansiedade INT NOT NULL,
    pontuacao_total_estresse INT NOT NULL,
    FOREIGN KEY (participante_id) REFERENCES Participantes(id)
);
*/